### ISSUE TITLE
Got error when running gau

### ISSUE THREAD

**Issue by navjot-rsa** [lc/gau#59]
**I got this error any solution???**
```
goroutine 1 [running]:
github.com/lc/gau/v2/pkg/providers/commoncrawl.New(0xc0001b2000, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...})
	/root/go/pkg/mod/github.com/lc/gau/v2@v2.0.6/pkg/providers/commoncrawl/commoncrawl.go:42 +0x1b0
github.com/lc/gau/v2/runner.(*Runner).Init(0xc000074690, 0xc0001b2000, 0x81a513)
	/root/go/pkg/mod/github.com/lc/gau/v2@v2.0.6/runner/runner.go:41 +0x585
main.main()
	/root/go/pkg/mod/github.com/lc/gau/v2@v2.0.6/cmd/gau/main.go:35 +0x23f
```

**Comment by sakyb7** [comment]
Facing the same issue...

**Comment by iamRjarpan** [comment]
Problem seems with `commoncrawl` so use `gau --providers wayback,otx,urlscan` untill there is fix released.

**Comment by navjot-rsa** [comment]
Thank you
